# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(	username:	"aaron11"	,	email:	"aaronf@yahoo.com"	,	description:	"I'm a software engineer and someone dedicated to making a positive impact on the world. I am not sure the exact outlet but I know technology will be involved. Someone said it's your rent for being on Earth. I am invested in what I do. Make an investment in me and we can do something possible but what's possible is more than what you think."	,	tagline:	"believe in the art of the possible, but what's possible is more than what you think"	,	zip:	"Oakland, CA"	,	profile_img_url:	"https://static1.squarespace.com/static/554553ade4b0ba2fd4eb10c4/55524958e4b008b6a454572a/55524b85e4b0c072ca6dd7dd/1431921973529/Ben_Franklin.jpg"	,	password:	"password"		)

User.create!(	username:	"marina64",	email:	"marinal@gmail.com"	,	description:	"I'm a Soviet refugee. I run a group of Soviet refugees now living in the United Statees. We're Americans dedicated to opposing Trump and his efforts against women, minorities, and the weakest in our society. Remember: First they came for the Socialists, and I did not speak out— Because I was not a Socialist. Then they came for the Trade Unionists, and I did not speak out— Because I was not a Trade Unionist. Then they came for the Jews, and I did not speak out— Because I was not a Jew. Then they came for me—and there was no one left to speak for me.",	tagline:	"Not that the story need be long, but it will take a long while to make it short. – Henry David Thoreau",	zip:	"Philadelphia, PA",	profile_img_url:	"http://vignette2.wikia.nocookie.net/dragon-rap-battles/images/a/a3/Thomas_Jefferson.png/revision/latest?cb=20151113180305",	password:	"password"		)
# #
User.create!(	username:	"TrevorW",	email:	"trevorwills@aol.com",	description: "I'm an eclectic dude. Different seed profiles lets me show different sides of personality. I'm a programmer with a lot of ideas. Give me a chance and it won't be smooth sailing always, but we'll accomplish great things that are truly different than the past"	,	tagline:	"just a human being trying to learn everyday",	zip:	"Fresno, CA",	profile_img_url:	"http://inmilitary.com/wp-content/uploads/2016/03/thumbnail-9df37bfb8d622105369a2adbcd693d21.jpeg"	,	password:	"password"		)

User.create!(	username:	"EricH"	,	email:	"eric.holds@dhs.ca.gov"	,	description:	"I was AG. I was kind of a disappointment at the job but now am excited to be entrepreneur and change society from the private sector rather than public office"	,	tagline:	"Not a father but looking forward to it"	,	zip:	"Upland, CA"	,	profile_img_url:	"http://imb.ulximg.com/image/src/artist/1260292104_8beaaa4db86dfbe49c87825d94d20c41.png/f7c84227490b9d0ad4b227f610108935/1260292104_jadakiss.png"	,	password:	"password")

User.create!(	username:	"SCurry",	email:	"curry@gsw.com"	,	description:	"It's amazing. Steph Curry, today's biggest basketball star (other than Lebron), is the opposite from Michael Jordan. Liked by teammates, seemingly driven to have fun, and a shooter, not a slasher/dunker. MJ lived to tear down opponents and settle slights. Steph is a better role model for today's young athletes IMHO"	,	tagline:	"I play more than basketball. The game doesn't define me"	,	zip:	"Tiburon, CA",	profile_img_url:	"https://upload.wikimedia.org/wikipedia/commons/1/10/Abraham-lincoln.png"	,	password:	"password")

User.create!(	username:	"NiaWillliams"	,	email:	"nialicious@gmail.com"	,	description:	"I'm Nia. It's an underrated name. More people should consider the name. Who wouldn't want to be remembered at their first introduction? I will not name a child any of top 10 names. I will not be a cog in a machine. I'm on Indieclono to start a business."	,	tagline:	"Actor. Philanthropist. Mother"	,	zip:	"Pomona, CA",	profile_img_url:	"http://pixel.nymag.com/imgs/daily/vulture/2015/09/22/22-taraji-p-henson-chatroom-silo.w190.h190.2x.png"	,	password:	"password"		)

User.create!(	username:	"darrell"	,	email:	"darrell916@gmail.com"	,	description:	"New to Indieclono, but heard good things. I'm hoping that this can lead to funding. I have a lot of ideas that could be pulled off with a small investment. If you interview me, ask me about some of them. Love to shoot the breeze about biz ideas. Software development will allow me to pursue these goals"	,	tagline:	"I love my hometown. Sacramento"	,	zip:	"Sacramento, CA	",	profile_img_url:	"http://ballnroll.com/wp-content/uploads/import/Blogs/Basketball/01worsttrades/image009.png"	,	password:	"password"		)

User.create!(	username:	"terrence"	,	email:	"terrence510@comcast.net"	,	description:	"Oakland is great. I loved living in LA while attending UCLA but Oakland might be my favorite place I've lived thus far. People are dedicated to the community and are more low-key. How much one pays in rent is not a status symbol. A lot of people in SF act like it should matter that they live in SF rather than East Bay"	,	tagline:	"Hello world. I'm not late. I'm right on time. "	,	zip:	"Hayward, CA"	,	profile_img_url:	"https://static1.squarespace.com/static/56d786ecc2ea51af915307f8/56fc5a7904426271cb8e9020/56fc5a8204426271cb8e9080/1459378837719/kendrick+lamar+4.png"	,	password:	"password"		)

User.create!(	username:	"confuciousjr"	,	email:	"confucious@hotmail.com"	,	description:	"I was deeply affected by the book, Thick Face, Black Heart. Check it out. It has a lot of interesting viewpoint that everything we love and hate in the world is a part of us. You must be somewhat detached to achieve your life's goal. It's a thick face because you don't emit emotions and a black heart because you don't let guilt or fear drive you."	,	tagline:	"Humanity hasn't changed that much. Let me tell you"	,	zip:	"Houston, TX	",	profile_img_url:	"https://thefilmstage.com/wp-content/uploads/2014/02/Screen-Shot-2014-02-04-at-7.43.32-PM.png"	,	password:	"password"		)
#

Campaign.create!(	title:	"Raspberry Pi's for the wonderful students at Oakland Tech High School"	,	description:	"Build clocks (heh...), build vocational skills, and perhaps, lead a few students to lifelong careers and passions."	,	location:	"Oakland, CA"	,	overview:	"Raspberry Pi is premier way to be introduced to semi-conductor, modern hardware, and a great way to spend a weekend. Could be a great experience for these kids. They're inexpensive, but not that inexpensive for a public school. I taught some volunteer SAT classes at the school and was so impressed with the young people. Always busy. Thoughtful about their future. Don't be afraid of the change they'll bring"	,	goal:	2500	,	status:	800	,	main_img_url:	"https://www.tweaking4all.com/wp-content/uploads/2015/04/raspberry-pi-2.jpg"	,	user_id:	3	,	category_id:	1	,	duration:	30	)

Campaign.create!(	title:	"Micro-Dosing Study",	description:	"Millennials Unite! Let's fund the definitive study on micro-dosing."	,	location:	"Denver, CO"	,	overview:	"Mental health prescriptions are not the only treatment. Many are discovering that microdosing psilocybin is improving their work, mood, and life. The funds will provide micro-doses to 150 volunteers and compensate pathologists/allergists/psychiatrists for monitoring efforts. Much of the effectiveness of prescription drugs is placebo effect. This is why a real experiment with a control group is needed to measure the impact. Micro-doses are often so small as to be indiscernible."	,	goal:	100000	,	status:	24000	,	main_img_url:	"http://www.mentalhealthy.co.uk/sites/default/files/Mental%20Health%20Help.jpg"	,	user_id:	2	,	category_id:	4	,	duration:	30	)

Campaign.create!(	title:	"Second Chance Lottery Machine"	,	description:	"An electronic machine to read and input 'second chance' Powerball lottery tickets."	,	location:	"Walnut Creek, CA"	,	overview:	"Each lottery ticket carries a code for a second chance lottery draw. Millions are won each year through these 'second chances.' Every bodega, corner store, and supermarket has tens if not hundreds of valid second chance lottery tickets in the garbage because it's a considerable pain to enter the tickets through Powerball's online interface. We want to build a scanner that can read the codes and then use software to enter the codes on Powerball's site. Just use Adobe for text reading and then figure out how a program could get past the captcha on the site. This could be big!"	,	goal:	10000	,	status:	8000	,	main_img_url:	"https://sophosnews.files.wordpress.com/2016/04/shutterstock_303181571.jpg?w=780&h=408&crop=1"	,	user_id:	2	,	category_id:	5	,	duration:	30	)

Campaign.create!(	title:	"Campaign to limit license plate readers"	,	description:	"Uncontrolled, unwarranted surveillance available to anyone that wants to buy...?"	,	location:	"Richmond, CA"	,	overview:	"A reporter did a public records request on Oakland PD and found that license plate readers had found his location 36 times in the month. He was not a former felon, a suspect or a person of interest in any crime. It was only incidental surveillance. This should concern reasonable people, not just conspiracy theorists. Tech industry should be a voice on this issue. Set up strong limits on law enforcement and the sale to private individuals."	,	goal:	20000	,	status:	14000	,	main_img_url:	"http://cityhallblog.dallasnewsblogs.com/files/2013/02/License-plate-reader.jpg"	,	user_id:	3	,	category_id:	7	,	duration:	30	)

Campaign.create!(	title:	"Build tent or shipping container cities and staff with healthcare services"	,	description:	"SF has over 1% of the nation's homeless while having just about 700,000 citizens."	,	location:	"San Francisco, CA"	,	overview:	"Affordable housing a is a pipe dream in a hyper expensive area. Provide lower income or homeless people with stable, safe housing with on-site nurse practitioner. The shipping containers have heaters and electricity. Put the containers near the 880 and provide the site with free public transportation including bus services. Mobility shouldn't be a privilege. Housing shouldn't be either. Housing is the great public policy issue of our time. Let's fund a two-year experiment. We'll have part-time work available to residents such as maintaining facilities and cleaning the premises."	,	goal:	750000	,	status:	390000	,	main_img_url:	"http://icdn4.digitaltrends.com/image/lil-1-640x427-c.jpg"	,	user_id:	3	,	category_id:	7	,	duration:	30	)

Campaign.create!(	title:	"Universal Basic Income Study"	,	description:	"The confluence of tech and consolidation of wealth requires action"	,	location:	"Sacramento, CA"	,	overview:	"We're taking off Y Combinator's basic income study with some important changes. We're providing a $1000 basic income to 100 people for 2 years. less than YC's. Rather than probe its effects on Oaklanders, already so close to tech and its economic opportunity. We're doing the study in Cincinnati, Ohio, a diverse community at a time of transition. How will people use the money? Will it benefit them in 'multiples'? We set no rules for what they must do with the money. Let's find out what happens."	,	goal:	300000	,	status:	96000	,	main_img_url:	"http://i0.wp.com/www.kickassfacts.com/wp-content/uploads/2016/05/Feat-1.jpg?fit=620%2C330"	,	user_id:	7	,	category_id:	7	,	duration:	30	)

Campaign.create!(	title:	"Extend hours at the Alameda Free Library"	,	description:	"Libraries are more important than ever. Education, community IRL, shelter, and internet"	,	location:	"Oakland, CA"	,	overview:	"It's a great library. I prepared a lot for App Academy there. It has private rooms, whiteboards, lots of space, a coffee shop downstairs, and regular folks. It's only open late a night or two a week. Speaking with staff once, they asserted that the hours could be solidly improved for just 35k. That's a Ford Escape. Let's make it happen. Libraries, for education, shelter, and the internet are critical to our community. It's a lot quieter than working at a Starbucks and you don't have to buy a burned espresso to have a seat and an outlet."	,	goal:	35000	,	status:	32000	,	main_img_url:	"http://1.bp.blogspot.com/-CYMJNDEe828/Vd4vX6vwjaI/AAAAAAAABXc/6d5YhgYPY-s/s1600/Alameda-Free-Library-3.jpg"	,	user_id:	1	,	category_id:	3	,	duration:	30	)

Campaign.create!(	title:	"Fund a class action suit against Comcast"	,	description:	"So many offenses, so little ability to take on a big company. Until now!"	,	location:	"Danville, CA"	,	overview:	"Comcast has been deceptive about its throttling and higher-end packages which grant unlimited data but slow your internet to a trickle. They've been caught red-handed. Let's make them pay. They must be aware that they're violating the law but with consumers lacking recourse, the practices continue. Courts are always tied up. Complex civil litigation takes years but should be a solid payoff at the end. Let's raise so much that they can't drown us by pointless, time-draining, money-depleting motions."	,	goal:	125000	,	status:	15000	,	main_img_url:	"http://www.crainsdetroit.com/apps/pbcsi.dll/storyimage/CD/20151227/NEWS/151229952/H1/0/H1-151229952.jpg?MaxW=880&v=201411210943"	,	user_id:	1	,	category_id:	3	,	duration:	30	)

Campaign.create!(	title:	"Fantasy football for high school!"	,	description:	"Let's use MaxPreps to gather stats and then clone DraftKings!"	,	location:	"Los Angeles, CA"	,	overview:	"Fantasy football is a monster. It's played a huge role in the NFL's dominance in sports and entertainment. I believe fantasy football for high schools could easily be implemented and could be popular. Fans could be closer to their actual teams and communities rather than millionaire mercernaries who have 40 inch verts. There's concern is that high school students could be harassed for their performance, but I don't feel it would be an issue since the stats would be based on past year's performance. Not real-time, week to week games. Let's build an app over a couple weekends."	,	goal:	15000	,	status:	1500	,	main_img_url:	"http://www.fantasysportstrophies.com/fantasyfootball.png"	,	user_id:	4	,	category_id:	4	,	duration:	30	)

Campaign.create!(	title:	"Empty the new asylums"	,	description:	"LA County Jail is the largest mental health facility in the US"	,	location:	"Los Angeles, CA"	,	overview:	"In 2016, an estimated 90,000 US jail inmates were pretrial defendants with serious mental illness who had been found incompetent to stand trial. IST services most commonly take place in state hospitals. Most state hospitals maintain waitlists of IST inmates because they do not have enough beds to meet demand. Waits are typically around one month but some are as long as a year. While the inmates wait, typically without treatment, they deteriorate, are often victimized and sometimes die. The findings of a mathematical model built to project whether relatively modest selected changes to the status quo could break this logjam. Data from five sample states were used for to model the effect of three specific changes. These recommendations are key to improving mental health facilities." ,	goal:	75000,
status:	30000,	main_img_url:	"http://affinitymagazine.us/wp-content/uploads/2017/02/mental-health.jpg"	,	user_id:	5	,	category_id:	4	,	duration:	30	)
# Campaign.create!(	title:	"New weight room at El Camino High School"	,	description:	"Weights are the only reason some come to school"	,	location:	"Carmichael, CA"	,	overview:	"We need 10k for new weight racks, a camera to monitor and provide feedback on athletes' swings, pitching motion, or power clean."	,	goal:	10000	,	status:	1100	,	main_img_url:	"http://www.ucbearcatsfootball.com/uploads/5/8/3/5/58352975/6545535_orig.png"	,	user_id:	6	,	category_id:	6	,	duration:	30	)
